name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Upload coverage data
        uses: codecov/codecov-action@v1

  release:
    name: Release
    needs: tests
    if: github.event_name == 'push' # Should always be on master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run
